#ifndef __UTILS_MAPITEST_MAPITEST_PROTO_H__
#define __UTILS_MAPITEST_MAPITEST_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)

#ifndef __BEGIN_DECLS
#ifdef __cplusplus
#define __BEGIN_DECLS		extern "C" {
#define __END_DECLS		}
#else
#define __BEGIN_DECLS
#define __END_DECLS
#endif
#endif

__BEGIN_DECLS

/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

/* this file contains prototypes for functions that are private 
 * to this subsystem or library. These functions should not be 
 * used outside this particular subsystem! */


/* The following definitions come from utils/mapitest/mapitest_suite.c  */


/* The following definitions come from utils/mapitest/mapitest_print.c  */


/* The following definitions come from utils/mapitest/mapitest_stat.c  */


/* The following definitions come from utils/mapitest/mapitest_common.c  */


/* The following definitions come from utils/mapitest/module.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcstor.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcfold.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcfxics.c  */


/* The following definitions come from utils/mapitest/modules/module_oxomsg.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcmsg.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcprpt.c  */


/* The following definitions come from utils/mapitest/modules/module_oxctable.c  */


/* The following definitions come from utils/mapitest/modules/module_oxorule.c  */


/* The following definitions come from utils/mapitest/modules/module_oxcnotif.c  */

int cb(uint16_t, void* , void* );

/* The following definitions come from utils/mapitest/modules/module_oxcperm.c  */


/* The following definitions come from utils/mapitest/modules/module_nspi.c  */


/* The following definitions come from utils/mapitest/modules/module_noserver.c  */


/* The following definitions come from utils/mapitest/modules/module_errorchecks.c  */


/* The following definitions come from utils/mapitest/modules/module_lcid.c  */


/* The following definitions come from utils/mapitest/modules/module_mapidump.c  */


/* The following definitions come from utils/mapitest/modules/module_lzxpress.c  */


__END_DECLS

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __UTILS_MAPITEST_MAPITEST_PROTO_H__ */

